// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Oracle.EntityFrameworkCore.Metadata;
using cadastro_de_dev.Data;

namespace cadastro_de_dev.Migrations
{
    [DbContext(typeof(CadastroDeDevContext))]
    [Migration("20201118005834_initial")]
    partial class initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn)
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            modelBuilder.Entity("cadastro_de_dev.Models.Desenvolvedor", b =>
                {
                    b.Property<long?>("DesenvolvedorID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Email")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<long?>("EmpresaID")
                        .HasColumnType("NUMBER(19)");

                    b.Property<string>("Nome")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.Property<string>("Telefone")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("DesenvolvedorID");

                    b.HasIndex("EmpresaID");

                    b.ToTable("Desenvolvedores");
                });

            modelBuilder.Entity("cadastro_de_dev.Models.DesenvolvedorLinguagem", b =>
                {
                    b.Property<long?>("LinguagemID")
                        .HasColumnType("NUMBER(19)");

                    b.Property<long?>("DesenvolvedorID")
                        .HasColumnType("NUMBER(19)");

                    b.HasKey("LinguagemID", "DesenvolvedorID");

                    b.HasIndex("DesenvolvedorID");

                    b.ToTable("DesenvolvedorLinguagens");
                });

            modelBuilder.Entity("cadastro_de_dev.Models.Empresa", b =>
                {
                    b.Property<long?>("EmpresaID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NomeEmpresa")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("EmpresaID");

                    b.ToTable("Empresas");
                });

            modelBuilder.Entity("cadastro_de_dev.Models.Linguagem", b =>
                {
                    b.Property<long?>("LinguagemID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("NUMBER(19)")
                        .HasAnnotation("Oracle:ValueGenerationStrategy", OracleValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("NomeLinguagem")
                        .HasColumnType("NVARCHAR2(2000)");

                    b.HasKey("LinguagemID");

                    b.ToTable("Linguagens");
                });

            modelBuilder.Entity("cadastro_de_dev.Models.Desenvolvedor", b =>
                {
                    b.HasOne("cadastro_de_dev.Models.Empresa", "Empresa")
                        .WithMany("Desenvolvedor")
                        .HasForeignKey("EmpresaID");
                });

            modelBuilder.Entity("cadastro_de_dev.Models.DesenvolvedorLinguagem", b =>
                {
                    b.HasOne("cadastro_de_dev.Models.Desenvolvedor", "Desenvolvedor")
                        .WithMany("DesenvolvedorLinguagem")
                        .HasForeignKey("DesenvolvedorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("cadastro_de_dev.Models.Linguagem", "Linguagem")
                        .WithMany("DesenvolvedorLinguagem")
                        .HasForeignKey("LinguagemID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
